# disabled_rules: # rule identifiers to exclude from running
#    - colon
#    - comma
#    - control_statement
#    - file_length
#    - force_cast
#    - force_try
#    - function_body_length
#    - leading_whitespace
#    - line_length
#    - nesting
#    - large_tuple
#    - unused_closure_parameter
#    - opening_brace
#    - operator_whitespace
#    - return_arrow_whitespace
#    - statement_position
#    - todo
#    - trailing_newline
#    - trailing_semicolon
#    - trailing_whitespace
#    - type_body_length
#    - type_name
#    - xctfail_message
#    - vertical_whitespace
#included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.

only_rules:
  - identifier_name

excluded: # paths to ignore during linting. overridden by `included`.
  - .build
  - .github
  - DevOpsTest.xcodeproj
  - Carthage
  - Pods
  - Modules
  - DevOpsTest/Assets.xcassets
  - DevOpsTest/DevOpsTest.xcdatamodelId
  - DevOpsTest/Preview Content

identifier_name:
  min_length: 5
  max_length: 20
  