name: Swift

on:
  push:
    branches: [ "citesting" ]
  pull_request:
    branches: [ "citesting" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: swift run swiftlint
    - name: Build and test base module with XCode
      run: xcodebuild clean test -scheme 'DevOpsTestTests' -destination 'platform=macOS' -showBuildTimingSummary
    - name: Build and test UI Tests with XCode
      run: xcodebuild clean test -scheme 'DevOpsTestUITests' -destination 'platform=macOS' -showBuildTimingSummary
    - name: Build final with XCode
      run: xcodebuild clean test -scheme 'DevOpsTest' -destination 'platform=macOS' -showBuildTimingSummary

